FROM rust:1-slim

# Target für WASM installieren
RUN rustup target add wasm32-unknown-unknown

# Optional: wasm-pack installieren, falls du Bindings für JavaScript/Browser benötigst
RUN apt-get update && apt-get install -y curl && \
    curl curl https://wasm-bindgen.github.io/wasm-pack/installer/init.sh -sSf | sh && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app